/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "DataResponse.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(environmentSensors_SingleDataPoint, environmentSensors_SingleDataPoint, AUTO)


PB_BIND(environmentSensors_DataResponse, environmentSensors_DataResponse, AUTO)



/* @@protoc_insertion_point(eof) */
