package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logging",
    srcs = ["logging.c"],
    hdrs = ["logging.h"],
    deps = ["//sensor:sensor"],
    linkopts = ["-pthread"],
)
