/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_ENVIRONMENTSENSORS_DATARESPONSE_PB_H_INCLUDED
#define PB_ENVIRONMENTSENSORS_DATARESPONSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _environmentSensors_SingleDataPoint {
    int32_t value;
    int32_t scale;
/* @@protoc_insertion_point(struct:environmentSensors_SingleDataPoint) */
} environmentSensors_SingleDataPoint;


typedef struct _environmentSensors_DataResponse {
    bool has_temperature;
    environmentSensors_SingleDataPoint temperature;
    bool has_humanity;
    environmentSensors_SingleDataPoint humanity;
    bool has_atmosphericPressure;
    environmentSensors_SingleDataPoint atmosphericPressure;
    bool has_pm2_5;
    environmentSensors_SingleDataPoint pm2_5;
/* @@protoc_insertion_point(struct:environmentSensors_DataResponse) */
} environmentSensors_DataResponse;


/* Initializer values for message structs */
#define environmentSensors_SingleDataPoint_init_default {0, 0}
#define environmentSensors_DataResponse_init_default {false, environmentSensors_SingleDataPoint_init_default, false, environmentSensors_SingleDataPoint_init_default, false, environmentSensors_SingleDataPoint_init_default, false, environmentSensors_SingleDataPoint_init_default}
#define environmentSensors_SingleDataPoint_init_zero {0, 0}
#define environmentSensors_DataResponse_init_zero {false, environmentSensors_SingleDataPoint_init_zero, false, environmentSensors_SingleDataPoint_init_zero, false, environmentSensors_SingleDataPoint_init_zero, false, environmentSensors_SingleDataPoint_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define environmentSensors_SingleDataPoint_value_tag 1
#define environmentSensors_SingleDataPoint_scale_tag 2
#define environmentSensors_DataResponse_temperature_tag 1
#define environmentSensors_DataResponse_humanity_tag 2
#define environmentSensors_DataResponse_atmosphericPressure_tag 3
#define environmentSensors_DataResponse_pm2_5_tag 4

/* Struct field encoding specification for nanopb */
#define environmentSensors_SingleDataPoint_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, INT32, value, 1) \
X(a, STATIC, REQUIRED, INT32, scale, 2)
#define environmentSensors_SingleDataPoint_CALLBACK NULL
#define environmentSensors_SingleDataPoint_DEFAULT NULL

#define environmentSensors_DataResponse_FIELDLIST(X, a) \
X(a, STATIC, OPTIONAL, MESSAGE, temperature, 1) \
X(a, STATIC, OPTIONAL, MESSAGE, humanity, 2) \
X(a, STATIC, OPTIONAL, MESSAGE, atmosphericPressure, 3) \
X(a, STATIC, OPTIONAL, MESSAGE, pm2_5, 4)
#define environmentSensors_DataResponse_CALLBACK NULL
#define environmentSensors_DataResponse_DEFAULT NULL
#define environmentSensors_DataResponse_temperature_MSGTYPE environmentSensors_SingleDataPoint
#define environmentSensors_DataResponse_humanity_MSGTYPE environmentSensors_SingleDataPoint
#define environmentSensors_DataResponse_atmosphericPressure_MSGTYPE environmentSensors_SingleDataPoint
#define environmentSensors_DataResponse_pm2_5_MSGTYPE environmentSensors_SingleDataPoint

extern const pb_msgdesc_t environmentSensors_SingleDataPoint_msg;
extern const pb_msgdesc_t environmentSensors_DataResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define environmentSensors_SingleDataPoint_fields &environmentSensors_SingleDataPoint_msg
#define environmentSensors_DataResponse_fields &environmentSensors_DataResponse_msg

/* Maximum encoded size of messages (where known) */
#define environmentSensors_SingleDataPoint_size  22
#define environmentSensors_DataResponse_size     96

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
